### ISSUE TITLE
issue in main and process.py

### ISSUE THREAD

**Issue by Abdul24-code** [lewjiayi/Crowd-Analysis#7]
main.py", line 79, in <module>
    processing_FPS = video_process(cap, FRAME_SIZE, net, ln, encoder, tracker, movement_data_writer, crowd_data_writer)
  File "C:\Users\91950\OneDrive\Desktop\Crowd-Analysis-main\video_process.py", line 55, in video_process
    TIME_STEP = DATA_RECORD_FRAME/VID_FPS
ZeroDivisionError: float division by zero

**Comment by lewjiayi** [comment]
What was your video input?

**Comment by Abdul24-code** [comment]
> @Abdul24-code What was your video input? VID_FPS retrieved in video_process.py line 53 `VID_FPS = cap.get(cv2.CAP_PROP_FPS)`, which reads your video input FPS. If this value is 0 then it should be your video input

my video input is zero i.e, VID_FPS=0 and DATA_RECORD_FRAME =1 .when i run main.py it shows zero division error : float division  error

**Comment by Abdul24-code** [comment]
video/7.mp4 file is missing , i couldn't find anywhwere

**Comment by lewjiayi** [comment]
The error happens because there is no video input, hence no fps can be read. You need to input a video source for the program. Put the path to the video at `VIDEO_CONFIG.VIDEO_CAP` in `config.py`. replace `video/7.mp4` with a video of your own. The video is not included in the repo. I will make an update on readme for that, thanks for letting me know!

**Comment by Abdul24-code** [comment]
> The error happens because there is no video input, hence no fps can be read. You need to input a video source for the program. Put the path to the video at `VIDEO_CONFIG.VIDEO_CAP` in `config.py`. replace `video/7.mp4` with a video of your own. The video is not included in the repo. I will make an update on readme for that, thanks for letting me know!

finally i am able to run this project successfully .it is possible by your support. thanks for giving your valuable time and support sir.

**Comment by abdulrahman2207** [comment]
which version python should be used here please tell me

**Comment by lewjiayi** [comment]
> which version python should be used here please tell me

Try 3.8 
Sorry I lost the record of the exact version, but I developed this in 2020. Python 3.8 was the latest
