### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Abdul24-code** [lewjiayi/Crowd-Analysis#8]
Hi sir

My friend is having some problem while deploying his project on heroku.
His app works fine on the localhost. But gives permission denied errno13.
He has tried using chmod chown command and every thing else he found on
the internet.  It would be of great help if u  could help him .
please

**Comment by lewjiayi** [comment]
@Abdul24-code Is your friend trying to deploy this project on heroku? I am not familiar with heroku. My advice is to post the whole error and maybe the whole project on some heroku discussion forum for help.

p/s: I will be removing this issue soon since it it irrelavant to the project. Good luck
